// AUTO-GENERATED by scripts/oklch-to-hex.ts. Do not edit by hand.
// Run: pnpm tokens
export const lightPalette = {
  bg: "#fbf8f4",
  surface: "#ffffff",
  "surface-2": "#f7f3ee",
  fg: "#1c140e",
  muted: "#5e5650",
  subtle: "#8c857f",
  border: "#e6e0da",
  "border-strong": "#c9c3bc",
  accent: "#c1291b",
  "accent-ink": "#890000",
  "accent-soft": "#ffe5df",
  teal: "#2c8671",
  highlight: "#ffdd93",
} as const;
export const darkPalette = {
  bg: "#120c07",
  surface: "#1b1510",
  "surface-2": "#221b16",
  fg: "#f1eeea",
  muted: "#a49d97",
  subtle: "#77706b",
  border: "#2e2722",
  "border-strong": "#49413a",
  accent: "#f56f57",
  "accent-ink": "#ffa693",
  "accent-soft": "#49150f",
  teal: "#57b9a1",
  highlight: "#6e5000",
} as const;
export type ThemeColor = keyof typeof lightPalette;
