// Convert oklch(L, C, H) to a sRGB hex string.
// L: 0..1, C: 0..0.4, H: degrees.
export function oklchToHex(l: number, c: number, h: number): string {
  const hRad = (h * Math.PI) / 180;
  const a = c * Math.cos(hRad);
  const b = c * Math.sin(hRad);

  const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = l - 0.0894841775 * a - 1.291485548 * b;

  const lc = l_ ** 3;
  const mc = m_ ** 3;
  const sc = s_ ** 3;

  let r = +4.0767416621 * lc - 3.3077115913 * mc + 0.2309699292 * sc;
  let g = -1.2684380046 * lc + 2.6097574011 * mc - 0.3413193965 * sc;
  let bl = -0.0041960863 * lc - 0.7034186147 * mc + 1.707614701 * sc;

  const toSrgb = (v: number) => (v <= 0.0031308 ? 12.92 * v : 1.055 * Math.pow(v, 1 / 2.4) - 0.055);
  r = toSrgb(r);
  g = toSrgb(g);
  bl = toSrgb(bl);

  const q = (v: number) =>
    Math.round(Math.min(Math.max(v, 0), 1) * 255)
      .toString(16)
      .padStart(2, "0");

  return `#${q(r)}${q(g)}${q(bl)}`;
}

type OklchTriple = readonly [number, number, number];

const LIGHT: Record<string, OklchTriple> = {
  bg: [0.98, 0.006, 70],
  surface: [1, 0, 0],
  "surface-2": [0.965, 0.008, 70],
  fg: [0.2, 0.018, 60],
  muted: [0.46, 0.014, 60],
  subtle: [0.62, 0.012, 60],
  border: [0.91, 0.01, 70],
  "border-strong": [0.82, 0.012, 70],
  accent: [0.53, 0.19, 30],
  "accent-ink": [0.38, 0.18, 30],
  "accent-soft": [0.945, 0.035, 30],
  teal: [0.56, 0.09, 175],
  highlight: [0.91, 0.1, 85],
};

const DARK: Record<string, OklchTriple> = {
  bg: [0.16, 0.014, 60],
  surface: [0.2, 0.014, 60],
  "surface-2": [0.23, 0.014, 60],
  fg: [0.95, 0.006, 70],
  muted: [0.7, 0.012, 60],
  subtle: [0.55, 0.012, 60],
  border: [0.28, 0.014, 60],
  "border-strong": [0.38, 0.016, 60],
  accent: [0.7, 0.17, 32],
  "accent-ink": [0.82, 0.12, 32],
  "accent-soft": [0.28, 0.08, 30],
  teal: [0.72, 0.1, 175],
  highlight: [0.45, 0.1, 85],
};

function emit(palette: Record<string, OklchTriple>) {
  const isIdent = (s: string) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);
  const entries = Object.entries(palette).map(([name, [l, c, h]]) => {
    const key = isIdent(name) ? name : `"${name}"`;
    return `  ${key}: "${oklchToHex(l, c, h)}",`;
  });
  return `{\n${entries.join("\n")}\n}`;
}

export function generate(): string {
  return [
    "// AUTO-GENERATED by scripts/oklch-to-hex.ts. Do not edit by hand.",
    "// Run: pnpm tokens",
    "export const lightPalette = " + emit(LIGHT) + " as const;",
    "export const darkPalette = " + emit(DARK) + " as const;",
    "export type ThemeColor = keyof typeof lightPalette;",
    "",
  ].join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  void (async () => {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    const out = path.resolve("src/theme/tokens.generated.ts");
    await fs.writeFile(out, generate(), "utf8");
    console.log("Wrote", out);
  })();
}
